"""
RAG Engine Service.

Orchestrates secure local document ingestion, embedding generation, FAISS indexing,
context retrieval, and grounded answer generation using local Ollama (qwen2.5:3b).

SECURITY INVARIANT:
Original unredacted confidential documents are strictly rejected from entering
the vector store and LLM. Only sanitized/redacted documents are permitted.
"""

from pathlib import Path
from typing import List, Optional, Union
from pydantic import BaseModel, Field

from app.services.vector_store import LocalVectorStore, DocumentChunk
from app.services.document_parser import DocumentParser
from app.services.ollama_client import OllamaClient, OllamaServiceError
from app.services.classifier import DocumentClassifier, SensitivityLevel
from app.services.redactor import DocumentRedactor


class SecurityViolationError(Exception):
    """Raised when an unredacted confidential document attempts to enter the RAG pipeline."""
    pass


class IngestionSummary(BaseModel):
    source_file: str = Field(..., description="File name of the ingested document")
    chunks_created: int = Field(..., description="Total number of chunks produced")
    total_indexed_chunks: int = Field(..., description="Total chunks now present in the vector store")
    storage_directory: str = Field(..., description="Directory where vector index is saved")


class SourceCitation(BaseModel):
    source_file: str = Field(..., description="Source document name")
    chunk_index: int = Field(..., description="1-indexed chunk number")
    chunk_id: str = Field(..., description="Full chunk identifier")


class RAGAnswer(BaseModel):
    question: str = Field(..., description="User's original question")
    answer: str = Field(..., description="Grounded answer generated by local LLM")
    sources: List[str] = Field(default_factory=list, description="List of source file and chunk citations")
    retrieved_chunks: List[DocumentChunk] = Field(default_factory=list, description="Context chunks used to answer")


class RAGEngine:
    """
    Local RAG engine integrating DocumentParser, FAISS VectorStore, and local Ollama.
    """

    SYSTEM_PROMPT = (
        "You are a secure, reliable onboarding assistant for company employees.\n"
        "Answer the user's question using ONLY the provided document context chunks.\n\n"
        "CRITICAL SECURITY AND ACCURACY RULES:\n"
        "1. Do NOT guess, extrapolate, or invent facts outside the provided context.\n"
        "2. If an item in the context is marked as [REDACTED], explicitly state that the information "
        "is redacted or unavailable. Never attempt to guess or reconstruct redacted values.\n"
        "3. If the provided context does not contain enough information to answer the question, clearly state: "
        "\"The requested information was not found in the provided documents.\"\n"
        "4. Keep your answer direct, clear, and professional."
    )

    def __init__(
        self,
        ollama_client: Optional[OllamaClient] = None,
        vector_store: Optional[LocalVectorStore] = None,
        document_parser: Optional[DocumentParser] = None,
        storage_dir: Union[str, Path] = "data/vector_store"
    ):
        self.ollama_client = ollama_client or OllamaClient()
        self.vector_store = vector_store or LocalVectorStore()
        self.document_parser = document_parser or DocumentParser()
        self.storage_dir = Path(storage_dir)

        self.classifier = DocumentClassifier()
        self.redactor = DocumentRedactor()

        # Attempt to load existing index from storage if available
        self.vector_store.load(self.storage_dir)

    def validate_document_security(self, text: str, filename: str) -> None:
        """
        Validate that the document is safe for RAG ingestion.
        Strictly rejects documents containing unredacted credentials or confidential financial data.
        """
        redaction_res = self.redactor.redact(text)
        classification_res = self.classifier.classify(
            text=text,
            detected_entity_types=redaction_res.detected_entity_types
        )

        # If entities like API_KEY, PASSWORD, AADHAAR, BANK_ACCOUNT, SALARY, PAN are detected unredacted
        critical_unredacted = [
            e for e in redaction_res.detected_entities
            if e.entity_type in ["API_KEY", "PASSWORD", "AADHAAR", "BANK_ACCOUNT", "SALARY", "PAN"]
            and e.value.strip() != "[REDACTED]"
        ]

        if critical_unredacted:
            detected_types = sorted(list({e.entity_type for e in critical_unredacted}))
            raise SecurityViolationError(
                f"Security Violation: '{filename}' contains unredacted confidential/restricted data "
                f"({', '.join(detected_types)}). Original confidential documents must never enter "
                f"the RAG or LLM pipeline. Please run 'python -m app.cli redact <file>' and ingest "
                f"the redacted file instead."
            )

    def ingest_document(self, file_path: Union[str, Path]) -> IngestionSummary:
        """
        Ingest a redacted document:
        1. Validates document security (rejects unredacted confidential files).
        2. Chunks the document.
        3. Generates local embeddings via Ollama.
        4. Indexes chunks into FAISS vector store.
        5. Persists index and metadata to disk.
        """
        p = Path(file_path).resolve()
        if not p.exists():
            raise FileNotFoundError(f"File not found: {file_path}")

        raw_text = p.read_text(encoding="utf-8")

        # Strict security enforcement
        self.validate_document_security(raw_text, p.name)

        # Chunk document
        chunks = self.document_parser.chunk_text(raw_text, source_name=p.name)
        if not chunks:
            raise ValueError(f"Document contains no chunkable text: {file_path}")

        # Generate embeddings locally
        embeddings: List[List[float]] = []
        for chunk in chunks:
            emb = self.ollama_client.get_embedding(chunk.content)
            embeddings.append(emb)

        # Store in FAISS
        self.vector_store.add_chunks(chunks, embeddings)
        self.vector_store.save(self.storage_dir)

        return IngestionSummary(
            source_file=p.name,
            chunks_created=len(chunks),
            total_indexed_chunks=self.vector_store.total_chunks,
            storage_directory=str(self.storage_dir)
        )

    def query(self, question: str, top_k: int = 3) -> RAGAnswer:
        """
        Answer a question using retrieved redacted context chunks and local Ollama (qwen2.5:3b).
        """
        # Ensure index is loaded
        if self.vector_store.total_chunks == 0:
            self.vector_store.load(self.storage_dir)

        if self.vector_store.total_chunks == 0:
            return RAGAnswer(
                question=question,
                answer=(
                    "No documents have been indexed yet. Please ingest a redacted document first "
                    "using: python -m app.cli ingest <redacted_file>"
                ),
                sources=[],
                retrieved_chunks=[]
            )

        # 1. Embed query
        query_embedding = self.ollama_client.get_embedding(question)

        # 2. Retrieve top_k chunks
        search_results = self.vector_store.search(query_embedding, top_k=top_k)

        if not search_results:
            return RAGAnswer(
                question=question,
                answer="The requested information was not found in the provided documents.",
                sources=[],
                retrieved_chunks=[]
            )

        retrieved_chunks = [chunk for chunk, _ in search_results]

        # 3. Format source citations
        sources: List[str] = []
        context_blocks: List[str] = []
        for chunk in retrieved_chunks:
            citation = f"{chunk.source_file} (chunk {chunk.chunk_index})"
            if citation not in sources:
                sources.append(citation)
            context_blocks.append(
                f"[Source: {chunk.source_file}, Chunk {chunk.chunk_index}]\n{chunk.content}"
            )

        context_str = "\n\n".join(context_blocks)

        # 4. Construct grounded prompt
        prompt = (
            f"Context:\n{context_str}\n\n"
            f"Question: {question}\n"
            "Answer:"
        )

        # 5. Call Ollama qwen2.5:3b
        llm_response = self.ollama_client.generate(prompt=prompt, system=self.SYSTEM_PROMPT)

        return RAGAnswer(
            question=question,
            answer=llm_response,
            sources=sources,
            retrieved_chunks=retrieved_chunks
        )
